add variables

diff --git a/Taskfile.yaml b/Taskfile.yaml
--- a/Taskfile.yaml
+++ b/Taskfile.yaml
@@ -1,14 +1,28 @@
 version: "3"
+vars:
+  worker_count: 2
+  jmx_file: "basic-plan.jmx"
+  kubernetes_namespace: "jmeter"
+  timeout: "7200"
+  input_folder: "../draft/project"
+  output_folder: "../out"
+  install_plugins: "true"
+  install_list_plugins: ""
 
 env:
-  TF_VAR_JMETER_WORKERS_COUNT: 2
-  TF_VAR_JMETER_CONF_EXEC_TIMEOUT: 7200
-  TF_VAR_namespace: "jmeter"
-  TF_VAR_JMETER_JMX_FILE: "basic-plan.jmx"
-  TF_VAR_JMETER_PLUGINS_MANAGER_INSTALL_FOR_JMX: true
-  TF_VAR_JMETER_PIPELINE_CLI_ARGUMENTS: " -Jblazemeter.upload.token:7 "
-  JMETER_DIRECTORY_INPUT: ../draft/project
-  JMETER_DIRECTORY_OUTPUT: ../out
+  TF_VAR_JMETER_WORKERS_COUNT: "{{.worker_count}}"
+  TF_VAR_JMETER_CONF_EXEC_TIMEOUT: "{{.timeout}}"
+  TF_VAR_namespace: "{{.kubernetes_namespace}}"
+  TF_VAR_JMETER_JMX_FILE: "{{.jmx_file}}"
+  TF_VAR_JMETER_PIPELINE_CLI_ARGUMENTS: ""
+  TF_VAR_JMETER_PLUGINS_MANAGER_INSTALL_FOR_JMX: "{{.install_plugins}}"
+  TF_VAR_JMETER_PLUGINS_MANAGER_INSTALL_LIST: "{{.install_list_plugins}}"
+  TF_VAR_JMETER_CONF_CSV_SPLIT_PATTERN: "**_split.csv"
+  TF_VAR_JMETER_CONF_CSV_DIVIDED_TO_OUT: "false"
+  TF_VAR_JMETER_PROPERTIES_FILES: ""
+  LOCAL_JMETER_DIRECTORY_INPUT: "{{.input_folder}}"
+  LOCAL_JMETER_DIRECTORY_OUTPUT: "{{.output_folder}}"
+
 output: prefixed
 
 tasks:
@@ -18,11 +32,10 @@ tasks:
       - task: prepare
       - task: copy-project
       - task: wait-test-follow
+      - task: check-jmeter-exitcode
       - task: get-result-controller
       - task: display-pod-logs
       - task: get-logs-workers
-
-
 
   validate:
     desc: validate Terraform
@@ -48,7 +61,7 @@ tasks:
     dir: ./terraform
     cmds:
       - |
-        PROJECT_FOLDER=$JMETER_DIRECTORY_INPUT
+        PROJECT_FOLDER=$LOCAL_JMETER_DIRECTORY_INPUT
         NAME_SPACE=$(terraform output --raw namespace)
         CONTROLLER_NAME=$(terraform output --raw jmeter_controller_name)
         WORKER_NAMES=$(terraform output --raw jmeter_workers_names)
@@ -97,7 +110,7 @@ tasks:
     dir: ./terraform
     cmds:
       - |
-        PROJECT_FOLDER=$JMETER_DIRECTORY_INPUT
+        PROJECT_FOLDER=$LOCAL_JMETER_DIRECTORY_INPUT
         NAME_SPACE=$(terraform output --raw namespace)
         CONTROLLER_NAME=$(terraform output --raw jmeter_controller_name)
         WORKER_NAMES=$(terraform output --raw jmeter_workers_names)
@@ -137,19 +150,32 @@ tasks:
         done
         echo "$(date): End!"
 
-        exitcode=$(kubectl get pods -n $NAME_SPACE $CONTROLLER_NAME -o=jsonpath='{.status.containerStatuses[0].state.terminated.exitCode}')
-        echo "Pod $CONTROLLER_NAME exitcode : $exitcode"
-        if [[ "$exitcode" != "0" ]]; then
-          echo "ERROR exitcode :  $exitcode"
-          exit 1
-        fi
+  check-jmeter-exitcode:
+    desc: copy project to
+    dir: ./terraform
+    cmds:
+      - |
+        PROJECT_FOLDER=$LOCAL_JMETER_DIRECTORY_INPUT
+        NAME_SPACE=$(terraform output --raw namespace)
+        CONTROLLER_NAME=$(terraform output --raw jmeter_controller_name)
+        WORKER_NAMES=$(terraform output --raw jmeter_workers_names)
+        echo "-----------------------------------------------------------------------------------------------------------------------------"
+
+        for instance in $CONTROLLER_NAME $WORKER_NAMES ; do
+          exitcode=$(kubectl get pods -n $NAME_SPACE $instance -o=jsonpath='{.status.containerStatuses[0].state.terminated.exitCode}')
+          echo "Pod $instance exitcode : $exitcode"
+          if [[ "$exitcode" != "0" ]]; then
+            echo "ERROR exitcode :  $exitcode"
+            exit 1
+          fi
+        done
 
   display-pod-logs:
     desc: copy project to
     dir: ./terraform
     cmds:
       - |
-        PROJECT_FOLDER=$JMETER_DIRECTORY_INPUT
+        PROJECT_FOLDER=$LOCAL_JMETER_DIRECTORY_INPUT
         NAME_SPACE=$(terraform output --raw namespace)
         CONTROLLER_NAME=$(terraform output --raw jmeter_controller_name)
         WORKER_NAMES=$(terraform output --raw jmeter_workers_names)
@@ -169,7 +195,7 @@ tasks:
     dir: ./terraform
     cmds:
       - |
-        mkdir -p $JMETER_DIRECTORY_OUTPUT
+        mkdir -p $LOCAL_JMETER_DIRECTORY_OUTPUT
         NAME_SPACE=$(terraform output --raw namespace)
         CONTROLLER_NAME=$(terraform output --raw jmeter_controller_name)
         echo "Start get Result"
@@ -178,8 +204,8 @@ tasks:
         for instance in $CONTROLLER_NAME; do
             echo "-----------------------------------------------------------------------------------------------------------------------------"
             echo "get Result from pod : $instance"
-            echo "kubectl cp -v 0 -n $NAME_SPACE -c keepalive $instance:/jmeter/out  $JMETER_DIRECTORY_OUTPUT "
-            kubectl cp -v 0 -n $NAME_SPACE -c keepalive $instance:/jmeter/out  $JMETER_DIRECTORY_OUTPUT 
+            echo "kubectl cp -v 0 -n $NAME_SPACE -c keepalive $instance:/jmeter/out  $LOCAL_JMETER_DIRECTORY_OUTPUT "
+            kubectl cp -v 0 -n $NAME_SPACE -c keepalive $instance:/jmeter/out  $LOCAL_JMETER_DIRECTORY_OUTPUT 
         done
         echo "Start get Result"
 
@@ -196,8 +222,8 @@ tasks:
         for instance in $WORKER_NAMES; do
             echo "-----------------------------------------------------------------------------------------------------------------------------"
             echo "get Result from pod : $instance"
-            echo "kubectl cp -v 0 -n $NAME_SPACE -c keepalive $instance:/jmeter/out  $JMETER_DIRECTORY_OUTPUT "
-            kubectl cp -v 0 -n $NAME_SPACE -c keepalive $instance:/jmeter/out  $JMETER_DIRECTORY_OUTPUT 
+            echo "kubectl cp -v 0 -n $NAME_SPACE -c keepalive $instance:/jmeter/out  $LOCAL_JMETER_DIRECTORY_OUTPUT "
+            kubectl cp -v 0 -n $NAME_SPACE -c keepalive $instance:/jmeter/out  $LOCAL_JMETER_DIRECTORY_OUTPUT 
         done
         echo "Start get Result"
 
